/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/material/dialog/dialog';
import * as import9 from '@angular/material/snack-bar/snack-bar';
import * as import10 from './app.component.css.shim.ngstyle';
import * as import11 from '@angular/material/sidenav/sidenav';
import * as import12 from '../node_modules/@angular/material/sidenav/sidenav.ngfactory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import15 from '@angular/material/toolbar/toolbar';
import * as import16 from '../node_modules/@angular/material/toolbar/toolbar.ngfactory';
import * as import17 from '@angular/material/button/button';
import * as import18 from '../node_modules/@angular/material/button/button.ngfactory';
import * as import19 from '../../app/album/album.component';
import * as import20 from './album/album.component.ngfactory';
import * as import21 from '@angular/material/progress-bar/progress-bar';
import * as import22 from '../node_modules/@angular/material/progress-bar/progress-bar.ngfactory';
import * as import23 from '@angular/core/src/change_detection/change_detection_util';
import * as import24 from '@angular/material/core/rtl/dir';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from '../../app/album/album.service';
import * as import27 from '@angular/material/core/compatibility/style-compatibility';
import * as import28 from '@angular/material/dialog/dialog-ref';
export class Wrapper_Material2AppAppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.Material2AppAppComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.Material2AppAppComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
export class Wrapper_DialogContent {
  /*private*/ _eventHandler:Function;
  context:import0.DialogContent;
  /*private*/ _changed:boolean;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.DialogContent(p0);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_Material2AppAppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_Material2AppAppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.Material2AppAppComponent>;
  _Material2AppAppComponent_0_3:Wrapper_Material2AppAppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Material2AppAppComponent_Host0,renderType_Material2AppAppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'material2-app-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_Material2AppAppComponent0(this.viewUtils,this,0,this._el_0);
    this._Material2AppAppComponent_0_3 = new Wrapper_Material2AppAppComponent(this.injectorGet(import8.MdDialog,this.parentIndex),this.injectorGet(import9.MdSnackBar,this.parentIndex));
    this.compView_0.create(this._Material2AppAppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._Material2AppAppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Material2AppAppComponent) && (0 === requestNodeIndex))) { return this._Material2AppAppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Material2AppAppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const Material2AppAppComponentNgFactory:import7.ComponentFactory<import0.Material2AppAppComponent> = new import7.ComponentFactory<import0.Material2AppAppComponent>('material2-app-app',View_Material2AppAppComponent_Host0,import0.Material2AppAppComponent);
const styles_Material2AppAppComponent:any[] = [import10.styles];
var renderType_Material2AppAppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_Material2AppAppComponent,{});
export class View_Material2AppAppComponent0 extends import1.AppView<import0.Material2AppAppComponent> {
  _el_0:any;
  compView_0:import1.AppView<import11.MdSidenavLayout>;
  _MdSidenavLayout_0_3:import12.Wrapper_MdSidenavLayout;
  _query_MdSidenav_0_0:import13.QueryList<any>;
  _text_1:any;
  _el_2:any;
  compView_2:import1.AppView<import11.MdSidenav>;
  _MdSidenav_2_3:import12.Wrapper_MdSidenav;
  _StyleCompatibility_2_4:import14.Wrapper_StyleCompatibility;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import15.MdToolbar>;
  _MdToolbar_5_3:import16.Wrapper_MdToolbar;
  _StyleCompatibility_5_4:import14.Wrapper_StyleCompatibility;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  compView_15:import1.AppView<import17.MdButton>;
  _MdButton_15_3:import18.Wrapper_MdButton;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  compView_21:import1.AppView<import19.AlbumComponent>;
  _AlbumComponent_21_3:import20.Wrapper_AlbumComponent;
  _text_22:any;
  _el_23:any;
  compView_23:import1.AppView<import21.MdProgressBar>;
  _MdProgressBar_23_3:import22.Wrapper_MdProgressBar;
  _StyleCompatibility_23_4:import14.Wrapper_StyleCompatibility;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_44:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_Material2AppAppComponent0,renderType_Material2AppAppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_44 = import23.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'md-sidenav-layout',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_0 = new import12.View_MdSidenavLayout0(this.viewUtils,this,0,this._el_0);
    this._MdSidenavLayout_0_3 = new import12.Wrapper_MdSidenavLayout(this.parentView.injectorGet(import24.Dir,this.parentIndex,(null as any)),new import25.ElementRef(this._el_0),this.renderer);
    this._query_MdSidenav_0_0 = new import13.QueryList<any>();
    this._text_1 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,(null as any),'md-sidenav',new import3.InlineArray4(4,'class','app-sidenav','mode','side'),(null as any));
    this.compView_2 = new import12.View_MdSidenav0(this.viewUtils,this,2,this._el_2);
    this._MdSidenav_2_3 = new import12.Wrapper_MdSidenav(new import25.ElementRef(this._el_2));
    this._StyleCompatibility_2_4 = new import14.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText((null as any),'\n        Sidenav\n    ',(null as any));
    this.compView_2.create(this._MdSidenav_2_3.context);
    this._text_4 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,(null as any),'md-toolbar',new import3.InlineArray2(2,'color','primary'),(null as any));
    this.compView_5 = new import16.View_MdToolbar0(this.viewUtils,this,5,this._el_5);
    this._MdToolbar_5_3 = new import16.Wrapper_MdToolbar(new import25.ElementRef(this._el_5),this.renderer);
    this._StyleCompatibility_5_4 = new import14.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_5));
    this._text_6 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','app-icon-button'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'i',new import3.InlineArray2(2,'class','material-icons app-toolbar-menu'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'menu',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n\n        Album Organizer!!\n\n        ',(null as any));
    this._el_13 = import3.createRenderElement(this.renderer,(null as any),'span',new import3.InlineArray2(2,'class','app-toolbar-filler'),(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_15 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'md-button',''),(null as any));
    this.compView_15 = new import18.View_MdButton0(this.viewUtils,this,15,this._el_15);
    this._MdButton_15_3 = new import18.Wrapper_MdButton(new import25.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText((null as any),'TOGGLE DARK THEME',(null as any));
    this.compView_15.create(this._MdButton_15_3.context);
    this._text_17 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_5.create(this._MdToolbar_5_3.context);
    this._text_18 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','app-content'),(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'\n\n        ',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'app-album',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_21 = new import20.View_AlbumComponent0(this.viewUtils,this,21,this._el_21);
    this._AlbumComponent_21_3 = new import20.Wrapper_AlbumComponent(this.parentView.injectorGet(import26.AlbumService,this.parentIndex));
    this._text_22 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_23 = import3.createRenderElement(this.renderer,(null as any),'md-progress-bar',new import3.InlineArray16(12,'aria-label','Indeterminate progress-bar example','aria-valuemax','100','aria-valuemin','0','class','app-progress','mode','indeterminate','role','progressbar'),(null as any));
    this.compView_23 = new import22.View_MdProgressBar0(this.viewUtils,this,23,this._el_23);
    this._MdProgressBar_23_3 = new import22.Wrapper_MdProgressBar();
    this._StyleCompatibility_23_4 = new import14.Wrapper_StyleCompatibility(this.renderer,new import25.ElementRef(this._el_23));
    this.compView_23.create(this._MdProgressBar_23_3.context);
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this.compView_21.create(this._AlbumComponent_21_3.context);
    this._text_25 = this.renderer.createText(this._el_19,'\n\n    ',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n\n',(null as any));
    this.compView_0.create(this._MdSidenavLayout_0_3.context);
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_2,new import3.InlineArray2(2,'transitionend',(null as any)),this.eventHandler(this.handleEvent_2));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_7,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_7));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_15,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_15));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdSidenav) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MdSidenav_2_3.context; }
    if (((token === import27.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._StyleCompatibility_2_4.context; }
    if (((token === import17.MdButton) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._MdButton_15_3.context; }
    if (((token === import15.MdToolbar) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._MdToolbar_5_3.context; }
    if (((token === import27.StyleCompatibility) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._StyleCompatibility_5_4.context; }
    if (((token === import21.MdProgressBar) && (23 === requestNodeIndex))) { return this._MdProgressBar_23_3.context; }
    if (((token === import27.StyleCompatibility) && (23 === requestNodeIndex))) { return this._StyleCompatibility_23_4.context; }
    if (((token === import19.AlbumComponent) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._AlbumComponent_21_3.context; }
    if (((token === import11.MdSidenavLayout) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._MdSidenavLayout_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MdSidenavLayout_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    const currVal_2_0_0:any = 'side';
    this._MdSidenav_2_3.check_mode(currVal_2_0_0,throwOnChange,false);
    if (this._MdSidenav_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    const currVal_5_0_0:any = 'primary';
    this._MdToolbar_5_3.check_color(currVal_5_0_0,throwOnChange,false);
    if (this._MdToolbar_5_3.ngDoCheck(this,this._el_5,throwOnChange)) { this.compView_5.markAsCheckOnce(); }
    this._StyleCompatibility_5_4.ngDoCheck(this,this._el_5,throwOnChange);
    if (this._MdButton_15_3.ngDoCheck(this,this._el_15,throwOnChange)) { this.compView_15.markAsCheckOnce(); }
    this._AlbumComponent_21_3.ngDoCheck(this,this._el_21,throwOnChange);
    const currVal_23_0_0:any = 'indeterminate';
    this._MdProgressBar_23_3.check_mode(currVal_23_0_0,throwOnChange,false);
    if (this._MdProgressBar_23_3.ngDoCheck(this,this._el_23,throwOnChange)) { this.compView_23.markAsCheckOnce(); }
    this._StyleCompatibility_23_4.ngDoCheck(this,this._el_23,throwOnChange);
    if (!throwOnChange) {
      if (this._query_MdSidenav_0_0.dirty) {
        this._query_MdSidenav_0_0.reset([this._MdSidenav_2_3.context]);
        this._MdSidenavLayout_0_3.context._sidenavs = this._query_MdSidenav_0_0;
        this._query_MdSidenav_0_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._MdSidenav_2_3.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._MdSidenavLayout_0_3.context.ngAfterContentInit(); }
    }
    const currVal_44:any = this.context.isDarkTheme;
    if (import3.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_0,'m2app-dark',currVal_44);
      this._expr_44 = currVal_44;
    }
    this._MdSidenav_2_3.checkHost(this,this.compView_2,this._el_2,throwOnChange);
    this._MdButton_15_3.checkHost(this,this.compView_15,this._el_15,throwOnChange);
    this._MdProgressBar_23_3.checkHost(this,this.compView_23,this._el_23,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
    this.compView_2.internalDetectChanges(throwOnChange);
    this.compView_5.internalDetectChanges(throwOnChange);
    this.compView_15.internalDetectChanges(throwOnChange);
    this.compView_21.internalDetectChanges(throwOnChange);
    this.compView_23.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this.compView_2.destroy();
    this.compView_5.destroy();
    this.compView_15.destroy();
    this.compView_21.destroy();
    this.compView_23.destroy();
    this._MdSidenav_2_3.ngOnDestroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 0) && (ngContentIndex == 0))) { cb(this._el_2,ctx); }
    if (((nodeIndex == 0) && (ngContentIndex == 1))) {
      cb(this._text_1,ctx);
      cb(this._text_4,ctx);
      cb(this._el_5,ctx);
      cb(this._text_18,ctx);
      cb(this._el_19,ctx);
      cb(this._text_26,ctx);
    }
    if (((nodeIndex == 2) && (ngContentIndex == 0))) { cb(this._text_3,ctx); }
    if (((nodeIndex == 5) && (ngContentIndex == 0))) {
      cb(this._text_6,ctx);
      cb(this._el_7,ctx);
      cb(this._text_12,ctx);
      cb(this._el_13,ctx);
      cb(this._text_14,ctx);
      cb(this._el_15,ctx);
      cb(this._text_17,ctx);
    }
    if (((nodeIndex == 5) && (ngContentIndex == 1))) {  }
    if (((nodeIndex == 15) && (ngContentIndex == 0))) { cb(this._text_16,ctx); }
  }
  handleEvent_2(eventName:string,$event:any):boolean {
    this.compView_2.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdSidenav_2_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_7(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this._MdSidenav_2_3.context.toggle()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_15(eventName:string,$event:any):boolean {
    this.compView_15.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_15_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.isDarkTheme = !this.context.isDarkTheme)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_DialogContent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_DialogContent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.DialogContent>;
  _DialogContent_0_3:Wrapper_DialogContent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DialogContent_Host0,renderType_DialogContent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_DialogContent0(this.viewUtils,this,0,this._el_0);
    this._DialogContent_0_3 = new Wrapper_DialogContent(this.injectorGet(import28.MdDialogRef,this.parentIndex,(null as any)));
    this.compView_0.create(this._DialogContent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._DialogContent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DialogContent) && (0 === requestNodeIndex))) { return this._DialogContent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DialogContent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const DialogContentNgFactory:import7.ComponentFactory<import0.DialogContent> = new import7.ComponentFactory<import0.DialogContent>('ng-component',View_DialogContent_Host0,import0.DialogContent);
const styles_DialogContent:any[] = ([] as any[]);
var renderType_DialogContent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_DialogContent,{});
export class View_DialogContent0 extends import1.AppView<import0.DialogContent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  compView_14:import1.AppView<import17.MdButton>;
  _MdButton_14_3:import18.Wrapper_MdButton;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_DialogContent0,renderType_DialogContent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'This is a dialog',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,parentRenderNode,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_4,'label',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        This is a text box inside of a dialog.\n        ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_6,'input',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,parentRenderNode,'p',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,' ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray2(2,'md-button',''),(null as any));
    this.compView_14 = new import18.View_MdButton0(this.viewUtils,this,14,this._el_14);
    this._MdButton_14_3 = new import18.Wrapper_MdButton(new import25.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText((null as any),'CLOSE',(null as any));
    this.compView_14.create(this._MdButton_14_3.context);
    this._text_16 = this.renderer.createText(this._el_12,' ',(null as any));
    this._text_17 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray8(8,'click',(null as any),'mousedown',(null as any),'focus',(null as any),'blur',(null as any)),this.eventHandler(this.handleEvent_14));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.MdButton) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._MdButton_14_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdButton_14_3.ngDoCheck(this,this._el_14,throwOnChange)) { this.compView_14.markAsCheckOnce(); }
    this._MdButton_14_3.checkHost(this,this.compView_14,this._el_14,throwOnChange);
    this.compView_14.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_14.destroy();
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 14) && (ngContentIndex == 0))) { cb(this._text_15,ctx); }
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.compView_14.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._MdButton_14_3.handleEvent(eventName,$event) && result);
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.dialogRef.close(this._el_8.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}