/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/material/core/ripple/ripple';
import * as import6 from '@angular/material/button/button';
import * as import7 from '@angular/material/card/card';
import * as import8 from '@angular/material/checkbox/checkbox';
import * as import9 from '@angular/material/core/line/line';
import * as import10 from '@angular/material/grid-list/grid-list';
import * as import11 from '@angular/forms/src/directives';
import * as import12 from '@angular/forms/src/form_providers';
import * as import13 from '@angular/material/input/input';
import * as import14 from '@angular/material/list/list';
import * as import15 from '@angular/material/progress-bar/progress-bar';
import * as import16 from '@angular/material/progress-circle/progress-circle';
import * as import17 from '@angular/material/sidenav/sidenav';
import * as import18 from '@angular/material/core/portal/portal-directives';
import * as import19 from '@angular/material/tabs/tabs';
import * as import20 from '@angular/material/toolbar/toolbar';
import * as import21 from '@angular/material/core/rtl/dir';
import * as import22 from '@angular/material/core/a11y/index';
import * as import23 from '@angular/material/button-toggle/button-toggle';
import * as import24 from '@angular/material/core/overlay/overlay-directives';
import * as import25 from '@angular/material/dialog/dialog';
import * as import26 from '@angular/http/src/http_module';
import * as import27 from '@angular/material/icon/icon';
import * as import28 from '@angular/material/menu/menu';
import * as import29 from '@angular/material/radio/radio';
import * as import30 from '@angular/material/slider/slider';
import * as import31 from '@angular/material/slide-toggle/slide-toggle';
import * as import32 from '@angular/material/snack-bar/snack-bar';
import * as import33 from '@angular/material/tooltip/tooltip';
import * as import34 from '@angular/material/core/compatibility/style-compatibility';
import * as import35 from '@angular/material/module';
import * as import36 from 'ng2-pagination/dist/ng2-pagination';
import * as import37 from '@angular/common/src/localization';
import * as import38 from '@angular/core/src/application_init';
import * as import39 from '@angular/core/src/testability/testability';
import * as import40 from '@angular/core/src/application_ref';
import * as import41 from '@angular/core/src/linker/compiler';
import * as import42 from '@angular/material/core/gestures/MdGestureConfig';
import * as import43 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import44 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import45 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import46 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import47 from '@angular/core/src/animation/animation_queue';
import * as import48 from '@angular/core/src/linker/view_utils';
import * as import49 from '@angular/platform-browser/src/browser/title';
import * as import50 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import51 from '@angular/http/src/backends/browser_xhr';
import * as import52 from '@angular/http/src/base_response_options';
import * as import53 from '@angular/http/src/backends/xhr_backend';
import * as import54 from '@angular/http/src/base_request_options';
import * as import55 from '@angular/material/core/a11y/live-announcer';
import * as import56 from '@angular/material/core/a11y/interactivity-checker';
import * as import57 from '@angular/material/core/coordination/unique-selection-dispatcher';
import * as import58 from '@angular/material/core/overlay/overlay-container';
import * as import59 from '@angular/material/core/overlay/position/viewport-ruler';
import * as import60 from '@angular/material/core/overlay/position/overlay-position-builder';
import * as import61 from '@angular/material/core/overlay/overlay';
import * as import62 from '@angular/material/icon/icon-registry';
import * as import63 from 'ng2-pagination/dist/pagination.service';
import * as import64 from '../../app/album/album.service';
import * as import65 from '@angular/core/src/di/injector';
import * as import66 from '../node_modules/@angular/material/dialog/dialog-container.ngfactory';
import * as import67 from '../node_modules/@angular/material/snack-bar/snack-bar-container.ngfactory';
import * as import68 from '../node_modules/@angular/material/snack-bar/simple-snack-bar.ngfactory';
import * as import69 from '../node_modules/@angular/material/tooltip/tooltip.ngfactory';
import * as import70 from './app.component.ngfactory';
import * as import71 from '@angular/core/src/i18n/tokens';
import * as import72 from '@angular/core/src/application_tokens';
import * as import73 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import74 from '@angular/platform-browser/src/dom/events/key_events';
import * as import75 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import76 from '@angular/core/src/zone/ng_zone';
import * as import77 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import78 from '@angular/core/src/console';
import * as import79 from '@angular/core/src/error_handler';
import * as import80 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import81 from '@angular/platform-browser/src/dom/animation_driver';
import * as import82 from '@angular/core/src/render/api';
import * as import83 from '@angular/core/src/security';
import * as import84 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import85 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import86 from '@angular/http/src/interfaces';
import * as import87 from '@angular/http/src/http';
class MaterialAppModuleInjector extends import0.NgModuleInjector<import1.MaterialAppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _MdRippleModule_3:import5.MdRippleModule;
  _MdButtonModule_4:import6.MdButtonModule;
  _MdCardModule_5:import7.MdCardModule;
  _MdCheckboxModule_6:import8.MdCheckboxModule;
  _MdLineModule_7:import9.MdLineModule;
  _MdGridListModule_8:import10.MdGridListModule;
  _InternalFormsSharedModule_9:import11.InternalFormsSharedModule;
  _FormsModule_10:import12.FormsModule;
  _MdInputModule_11:import13.MdInputModule;
  _MdListModule_12:import14.MdListModule;
  _MdProgressBarModule_13:import15.MdProgressBarModule;
  _MdProgressCircleModule_14:import16.MdProgressCircleModule;
  _MdSidenavModule_15:import17.MdSidenavModule;
  _PortalModule_16:import18.PortalModule;
  _MdTabsModule_17:import19.MdTabsModule;
  _MdToolbarModule_18:import20.MdToolbarModule;
  _RtlModule_19:import21.RtlModule;
  _A11yModule_20:import22.A11yModule;
  _MdButtonToggleModule_21:import23.MdButtonToggleModule;
  _OverlayModule_22:import24.OverlayModule;
  _MdDialogModule_23:import25.MdDialogModule;
  _HttpModule_24:import26.HttpModule;
  _MdIconModule_25:import27.MdIconModule;
  _MdMenuModule_26:import28.MdMenuModule;
  _MdRadioModule_27:import29.MdRadioModule;
  _MdSliderModule_28:import30.MdSliderModule;
  _MdSlideToggleModule_29:import31.MdSlideToggleModule;
  _MdSnackBarModule_30:import32.MdSnackBarModule;
  _MdTooltipModule_31:import33.MdTooltipModule;
  _StyleCompatibilityModule_32:import34.StyleCompatibilityModule;
  _MaterialRootModule_33:import35.MaterialRootModule;
  _Ng2PaginationModule_34:import36.Ng2PaginationModule;
  _MaterialAppModule_35:import1.MaterialAppModule;
  __LOCALE_ID_36:any;
  __NgLocalization_37:import37.NgLocaleLocalization;
  _ErrorHandler_38:any;
  _ApplicationInitStatus_39:import38.ApplicationInitStatus;
  _Testability_40:import39.Testability;
  _ApplicationRef__41:import40.ApplicationRef_;
  __ApplicationRef_42:any;
  __Compiler_43:import41.Compiler;
  __APP_ID_44:any;
  __DOCUMENT_45:any;
  __HAMMER_GESTURE_CONFIG_46:import42.MdGestureConfig;
  __EVENT_MANAGER_PLUGINS_47:any[];
  __EventManager_48:import43.EventManager;
  _DomSharedStylesHost_49:import44.DomSharedStylesHost;
  __AnimationDriver_50:any;
  __DomRootRenderer_51:import45.DomRootRenderer_;
  __RootRenderer_52:any;
  __DomSanitizer_53:import46.DomSanitizerImpl;
  __Sanitizer_54:any;
  __AnimationQueue_55:import47.AnimationQueue;
  __ViewUtils_56:import48.ViewUtils;
  __IterableDiffers_57:any;
  __KeyValueDiffers_58:any;
  __SharedStylesHost_59:any;
  __Title_60:import49.Title;
  __RadioControlRegistry_61:import50.RadioControlRegistry;
  __BrowserXhr_62:import51.BrowserXhr;
  __ResponseOptions_63:import52.BaseResponseOptions;
  __XSRFStrategy_64:any;
  __XHRBackend_65:import53.XHRBackend;
  __RequestOptions_66:import54.BaseRequestOptions;
  __Http_67:any;
  __MdLiveAnnouncer_68:import55.MdLiveAnnouncer;
  __InteractivityChecker_69:import56.InteractivityChecker;
  __MdUniqueSelectionDispatcher_70:import57.MdUniqueSelectionDispatcher;
  __OverlayContainer_71:import58.OverlayContainer;
  __ViewportRuler_72:import59.ViewportRuler;
  __OverlayPositionBuilder_73:import60.OverlayPositionBuilder;
  __Overlay_74:import61.Overlay;
  __MdDialog_75:import25.MdDialog;
  __MdIconRegistry_76:import62.MdIconRegistry;
  __MdSnackBar_77:import32.MdSnackBar;
  __PaginationService_78:import63.PaginationService;
  __AlbumService_79:import64.AlbumService;
  constructor(parent:import65.Injector) {
    super(parent,[
      import66.MdDialogContainerNgFactory,
      import67.MdSnackBarContainerNgFactory,
      import68.SimpleSnackBarNgFactory,
      import69.TooltipComponentNgFactory,
      import70.DialogContentNgFactory,
      import70.Material2AppAppComponentNgFactory
    ]
    ,[import70.Material2AppAppComponentNgFactory]);
  }
  get _LOCALE_ID_36():any {
    if ((this.__LOCALE_ID_36 == null)) { (this.__LOCALE_ID_36 = import3._localeFactory(this.parent.get(import71.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_36;
  }
  get _NgLocalization_37():import37.NgLocaleLocalization {
    if ((this.__NgLocalization_37 == null)) { (this.__NgLocalization_37 = new import37.NgLocaleLocalization(this._LOCALE_ID_36)); }
    return this.__NgLocalization_37;
  }
  get _ApplicationRef_42():any {
    if ((this.__ApplicationRef_42 == null)) { (this.__ApplicationRef_42 = this._ApplicationRef__41); }
    return this.__ApplicationRef_42;
  }
  get _Compiler_43():import41.Compiler {
    if ((this.__Compiler_43 == null)) { (this.__Compiler_43 = new import41.Compiler()); }
    return this.__Compiler_43;
  }
  get _APP_ID_44():any {
    if ((this.__APP_ID_44 == null)) { (this.__APP_ID_44 = import72._appIdRandomProviderFactory()); }
    return this.__APP_ID_44;
  }
  get _DOCUMENT_45():any {
    if ((this.__DOCUMENT_45 == null)) { (this.__DOCUMENT_45 = import4._document()); }
    return this.__DOCUMENT_45;
  }
  get _HAMMER_GESTURE_CONFIG_46():import42.MdGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_46 == null)) { (this.__HAMMER_GESTURE_CONFIG_46 = new import42.MdGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_46;
  }
  get _EVENT_MANAGER_PLUGINS_47():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_47 == null)) { (this.__EVENT_MANAGER_PLUGINS_47 = [
      new import73.DomEventsPlugin(),
      new import74.KeyEventsPlugin(),
      new import75.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_46)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_47;
  }
  get _EventManager_48():import43.EventManager {
    if ((this.__EventManager_48 == null)) { (this.__EventManager_48 = new import43.EventManager(this._EVENT_MANAGER_PLUGINS_47,this.parent.get(import76.NgZone))); }
    return this.__EventManager_48;
  }
  get _AnimationDriver_50():any {
    if ((this.__AnimationDriver_50 == null)) { (this.__AnimationDriver_50 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_50;
  }
  get _DomRootRenderer_51():import45.DomRootRenderer_ {
    if ((this.__DomRootRenderer_51 == null)) { (this.__DomRootRenderer_51 = new import45.DomRootRenderer_(this._DOCUMENT_45,this._EventManager_48,this._DomSharedStylesHost_49,this._AnimationDriver_50,this._APP_ID_44)); }
    return this.__DomRootRenderer_51;
  }
  get _RootRenderer_52():any {
    if ((this.__RootRenderer_52 == null)) { (this.__RootRenderer_52 = import77._createConditionalRootRenderer(this._DomRootRenderer_51,this.parent.get(import77.NgProbeToken,(null as any)),this.parent.get(import40.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_52;
  }
  get _DomSanitizer_53():import46.DomSanitizerImpl {
    if ((this.__DomSanitizer_53 == null)) { (this.__DomSanitizer_53 = new import46.DomSanitizerImpl()); }
    return this.__DomSanitizer_53;
  }
  get _Sanitizer_54():any {
    if ((this.__Sanitizer_54 == null)) { (this.__Sanitizer_54 = this._DomSanitizer_53); }
    return this.__Sanitizer_54;
  }
  get _AnimationQueue_55():import47.AnimationQueue {
    if ((this.__AnimationQueue_55 == null)) { (this.__AnimationQueue_55 = new import47.AnimationQueue(this.parent.get(import76.NgZone))); }
    return this.__AnimationQueue_55;
  }
  get _ViewUtils_56():import48.ViewUtils {
    if ((this.__ViewUtils_56 == null)) { (this.__ViewUtils_56 = new import48.ViewUtils(this._RootRenderer_52,this._Sanitizer_54,this._AnimationQueue_55)); }
    return this.__ViewUtils_56;
  }
  get _IterableDiffers_57():any {
    if ((this.__IterableDiffers_57 == null)) { (this.__IterableDiffers_57 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_57;
  }
  get _KeyValueDiffers_58():any {
    if ((this.__KeyValueDiffers_58 == null)) { (this.__KeyValueDiffers_58 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_58;
  }
  get _SharedStylesHost_59():any {
    if ((this.__SharedStylesHost_59 == null)) { (this.__SharedStylesHost_59 = this._DomSharedStylesHost_49); }
    return this.__SharedStylesHost_59;
  }
  get _Title_60():import49.Title {
    if ((this.__Title_60 == null)) { (this.__Title_60 = new import49.Title()); }
    return this.__Title_60;
  }
  get _RadioControlRegistry_61():import50.RadioControlRegistry {
    if ((this.__RadioControlRegistry_61 == null)) { (this.__RadioControlRegistry_61 = new import50.RadioControlRegistry()); }
    return this.__RadioControlRegistry_61;
  }
  get _BrowserXhr_62():import51.BrowserXhr {
    if ((this.__BrowserXhr_62 == null)) { (this.__BrowserXhr_62 = new import51.BrowserXhr()); }
    return this.__BrowserXhr_62;
  }
  get _ResponseOptions_63():import52.BaseResponseOptions {
    if ((this.__ResponseOptions_63 == null)) { (this.__ResponseOptions_63 = new import52.BaseResponseOptions()); }
    return this.__ResponseOptions_63;
  }
  get _XSRFStrategy_64():any {
    if ((this.__XSRFStrategy_64 == null)) { (this.__XSRFStrategy_64 = import26._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_64;
  }
  get _XHRBackend_65():import53.XHRBackend {
    if ((this.__XHRBackend_65 == null)) { (this.__XHRBackend_65 = new import53.XHRBackend(this._BrowserXhr_62,this._ResponseOptions_63,this._XSRFStrategy_64)); }
    return this.__XHRBackend_65;
  }
  get _RequestOptions_66():import54.BaseRequestOptions {
    if ((this.__RequestOptions_66 == null)) { (this.__RequestOptions_66 = new import54.BaseRequestOptions()); }
    return this.__RequestOptions_66;
  }
  get _Http_67():any {
    if ((this.__Http_67 == null)) { (this.__Http_67 = import26.httpFactory(this._XHRBackend_65,this._RequestOptions_66)); }
    return this.__Http_67;
  }
  get _MdLiveAnnouncer_68():import55.MdLiveAnnouncer {
    if ((this.__MdLiveAnnouncer_68 == null)) { (this.__MdLiveAnnouncer_68 = new import55.MdLiveAnnouncer(this.parent.get(import55.LIVE_ANNOUNCER_ELEMENT_TOKEN,(null as any)))); }
    return this.__MdLiveAnnouncer_68;
  }
  get _InteractivityChecker_69():import56.InteractivityChecker {
    if ((this.__InteractivityChecker_69 == null)) { (this.__InteractivityChecker_69 = new import56.InteractivityChecker()); }
    return this.__InteractivityChecker_69;
  }
  get _MdUniqueSelectionDispatcher_70():import57.MdUniqueSelectionDispatcher {
    if ((this.__MdUniqueSelectionDispatcher_70 == null)) { (this.__MdUniqueSelectionDispatcher_70 = new import57.MdUniqueSelectionDispatcher()); }
    return this.__MdUniqueSelectionDispatcher_70;
  }
  get _OverlayContainer_71():import58.OverlayContainer {
    if ((this.__OverlayContainer_71 == null)) { (this.__OverlayContainer_71 = new import58.OverlayContainer()); }
    return this.__OverlayContainer_71;
  }
  get _ViewportRuler_72():import59.ViewportRuler {
    if ((this.__ViewportRuler_72 == null)) { (this.__ViewportRuler_72 = new import59.ViewportRuler()); }
    return this.__ViewportRuler_72;
  }
  get _OverlayPositionBuilder_73():import60.OverlayPositionBuilder {
    if ((this.__OverlayPositionBuilder_73 == null)) { (this.__OverlayPositionBuilder_73 = new import60.OverlayPositionBuilder(this._ViewportRuler_72)); }
    return this.__OverlayPositionBuilder_73;
  }
  get _Overlay_74():import61.Overlay {
    if ((this.__Overlay_74 == null)) { (this.__Overlay_74 = new import61.Overlay(this._OverlayContainer_71,this,this._OverlayPositionBuilder_73,this._ApplicationRef_42,this)); }
    return this.__Overlay_74;
  }
  get _MdDialog_75():import25.MdDialog {
    if ((this.__MdDialog_75 == null)) { (this.__MdDialog_75 = new import25.MdDialog(this._Overlay_74,this)); }
    return this.__MdDialog_75;
  }
  get _MdIconRegistry_76():import62.MdIconRegistry {
    if ((this.__MdIconRegistry_76 == null)) { (this.__MdIconRegistry_76 = new import62.MdIconRegistry(this._Http_67)); }
    return this.__MdIconRegistry_76;
  }
  get _MdSnackBar_77():import32.MdSnackBar {
    if ((this.__MdSnackBar_77 == null)) { (this.__MdSnackBar_77 = new import32.MdSnackBar(this._Overlay_74,this._MdLiveAnnouncer_68)); }
    return this.__MdSnackBar_77;
  }
  get _PaginationService_78():import63.PaginationService {
    if ((this.__PaginationService_78 == null)) { (this.__PaginationService_78 = new import63.PaginationService()); }
    return this.__PaginationService_78;
  }
  get _AlbumService_79():import64.AlbumService {
    if ((this.__AlbumService_79 == null)) { (this.__AlbumService_79 = new import64.AlbumService(this._Http_67)); }
    return this.__AlbumService_79;
  }
  createInternal():import1.MaterialAppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._MdRippleModule_3 = new import5.MdRippleModule();
    this._MdButtonModule_4 = new import6.MdButtonModule();
    this._MdCardModule_5 = new import7.MdCardModule();
    this._MdCheckboxModule_6 = new import8.MdCheckboxModule();
    this._MdLineModule_7 = new import9.MdLineModule();
    this._MdGridListModule_8 = new import10.MdGridListModule();
    this._InternalFormsSharedModule_9 = new import11.InternalFormsSharedModule();
    this._FormsModule_10 = new import12.FormsModule();
    this._MdInputModule_11 = new import13.MdInputModule();
    this._MdListModule_12 = new import14.MdListModule();
    this._MdProgressBarModule_13 = new import15.MdProgressBarModule();
    this._MdProgressCircleModule_14 = new import16.MdProgressCircleModule();
    this._MdSidenavModule_15 = new import17.MdSidenavModule();
    this._PortalModule_16 = new import18.PortalModule();
    this._MdTabsModule_17 = new import19.MdTabsModule();
    this._MdToolbarModule_18 = new import20.MdToolbarModule();
    this._RtlModule_19 = new import21.RtlModule();
    this._A11yModule_20 = new import22.A11yModule();
    this._MdButtonToggleModule_21 = new import23.MdButtonToggleModule();
    this._OverlayModule_22 = new import24.OverlayModule();
    this._MdDialogModule_23 = new import25.MdDialogModule();
    this._HttpModule_24 = new import26.HttpModule();
    this._MdIconModule_25 = new import27.MdIconModule();
    this._MdMenuModule_26 = new import28.MdMenuModule();
    this._MdRadioModule_27 = new import29.MdRadioModule();
    this._MdSliderModule_28 = new import30.MdSliderModule();
    this._MdSlideToggleModule_29 = new import31.MdSlideToggleModule();
    this._MdSnackBarModule_30 = new import32.MdSnackBarModule();
    this._MdTooltipModule_31 = new import33.MdTooltipModule();
    this._StyleCompatibilityModule_32 = new import34.StyleCompatibilityModule();
    this._MaterialRootModule_33 = new import35.MaterialRootModule();
    this._Ng2PaginationModule_34 = new import36.Ng2PaginationModule();
    this._MaterialAppModule_35 = new import1.MaterialAppModule();
    this._ErrorHandler_38 = import4.errorHandler();
    this._ApplicationInitStatus_39 = new import38.ApplicationInitStatus(this.parent.get(import38.APP_INITIALIZER,(null as any)));
    this._Testability_40 = new import39.Testability(this.parent.get(import76.NgZone));
    this._ApplicationRef__41 = new import40.ApplicationRef_(this.parent.get(import76.NgZone),this.parent.get(import78.Console),this,this._ErrorHandler_38,this,this._ApplicationInitStatus_39,this.parent.get(import39.TestabilityRegistry,(null as any)),this._Testability_40);
    this._DomSharedStylesHost_49 = new import44.DomSharedStylesHost(this._DOCUMENT_45);
    return this._MaterialAppModule_35;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.MdRippleModule)) { return this._MdRippleModule_3; }
    if ((token === import6.MdButtonModule)) { return this._MdButtonModule_4; }
    if ((token === import7.MdCardModule)) { return this._MdCardModule_5; }
    if ((token === import8.MdCheckboxModule)) { return this._MdCheckboxModule_6; }
    if ((token === import9.MdLineModule)) { return this._MdLineModule_7; }
    if ((token === import10.MdGridListModule)) { return this._MdGridListModule_8; }
    if ((token === import11.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_9; }
    if ((token === import12.FormsModule)) { return this._FormsModule_10; }
    if ((token === import13.MdInputModule)) { return this._MdInputModule_11; }
    if ((token === import14.MdListModule)) { return this._MdListModule_12; }
    if ((token === import15.MdProgressBarModule)) { return this._MdProgressBarModule_13; }
    if ((token === import16.MdProgressCircleModule)) { return this._MdProgressCircleModule_14; }
    if ((token === import17.MdSidenavModule)) { return this._MdSidenavModule_15; }
    if ((token === import18.PortalModule)) { return this._PortalModule_16; }
    if ((token === import19.MdTabsModule)) { return this._MdTabsModule_17; }
    if ((token === import20.MdToolbarModule)) { return this._MdToolbarModule_18; }
    if ((token === import21.RtlModule)) { return this._RtlModule_19; }
    if ((token === import22.A11yModule)) { return this._A11yModule_20; }
    if ((token === import23.MdButtonToggleModule)) { return this._MdButtonToggleModule_21; }
    if ((token === import24.OverlayModule)) { return this._OverlayModule_22; }
    if ((token === import25.MdDialogModule)) { return this._MdDialogModule_23; }
    if ((token === import26.HttpModule)) { return this._HttpModule_24; }
    if ((token === import27.MdIconModule)) { return this._MdIconModule_25; }
    if ((token === import28.MdMenuModule)) { return this._MdMenuModule_26; }
    if ((token === import29.MdRadioModule)) { return this._MdRadioModule_27; }
    if ((token === import30.MdSliderModule)) { return this._MdSliderModule_28; }
    if ((token === import31.MdSlideToggleModule)) { return this._MdSlideToggleModule_29; }
    if ((token === import32.MdSnackBarModule)) { return this._MdSnackBarModule_30; }
    if ((token === import33.MdTooltipModule)) { return this._MdTooltipModule_31; }
    if ((token === import34.StyleCompatibilityModule)) { return this._StyleCompatibilityModule_32; }
    if ((token === import35.MaterialRootModule)) { return this._MaterialRootModule_33; }
    if ((token === import36.Ng2PaginationModule)) { return this._Ng2PaginationModule_34; }
    if ((token === import1.MaterialAppModule)) { return this._MaterialAppModule_35; }
    if ((token === import71.LOCALE_ID)) { return this._LOCALE_ID_36; }
    if ((token === import37.NgLocalization)) { return this._NgLocalization_37; }
    if ((token === import79.ErrorHandler)) { return this._ErrorHandler_38; }
    if ((token === import38.ApplicationInitStatus)) { return this._ApplicationInitStatus_39; }
    if ((token === import39.Testability)) { return this._Testability_40; }
    if ((token === import40.ApplicationRef_)) { return this._ApplicationRef__41; }
    if ((token === import40.ApplicationRef)) { return this._ApplicationRef_42; }
    if ((token === import41.Compiler)) { return this._Compiler_43; }
    if ((token === import72.APP_ID)) { return this._APP_ID_44; }
    if ((token === import80.DOCUMENT)) { return this._DOCUMENT_45; }
    if ((token === import75.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_46; }
    if ((token === import43.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_47; }
    if ((token === import43.EventManager)) { return this._EventManager_48; }
    if ((token === import44.DomSharedStylesHost)) { return this._DomSharedStylesHost_49; }
    if ((token === import81.AnimationDriver)) { return this._AnimationDriver_50; }
    if ((token === import45.DomRootRenderer)) { return this._DomRootRenderer_51; }
    if ((token === import82.RootRenderer)) { return this._RootRenderer_52; }
    if ((token === import46.DomSanitizer)) { return this._DomSanitizer_53; }
    if ((token === import83.Sanitizer)) { return this._Sanitizer_54; }
    if ((token === import47.AnimationQueue)) { return this._AnimationQueue_55; }
    if ((token === import48.ViewUtils)) { return this._ViewUtils_56; }
    if ((token === import84.IterableDiffers)) { return this._IterableDiffers_57; }
    if ((token === import85.KeyValueDiffers)) { return this._KeyValueDiffers_58; }
    if ((token === import44.SharedStylesHost)) { return this._SharedStylesHost_59; }
    if ((token === import49.Title)) { return this._Title_60; }
    if ((token === import50.RadioControlRegistry)) { return this._RadioControlRegistry_61; }
    if ((token === import51.BrowserXhr)) { return this._BrowserXhr_62; }
    if ((token === import52.ResponseOptions)) { return this._ResponseOptions_63; }
    if ((token === import86.XSRFStrategy)) { return this._XSRFStrategy_64; }
    if ((token === import53.XHRBackend)) { return this._XHRBackend_65; }
    if ((token === import54.RequestOptions)) { return this._RequestOptions_66; }
    if ((token === import87.Http)) { return this._Http_67; }
    if ((token === import55.MdLiveAnnouncer)) { return this._MdLiveAnnouncer_68; }
    if ((token === import56.InteractivityChecker)) { return this._InteractivityChecker_69; }
    if ((token === import57.MdUniqueSelectionDispatcher)) { return this._MdUniqueSelectionDispatcher_70; }
    if ((token === import58.OverlayContainer)) { return this._OverlayContainer_71; }
    if ((token === import59.ViewportRuler)) { return this._ViewportRuler_72; }
    if ((token === import60.OverlayPositionBuilder)) { return this._OverlayPositionBuilder_73; }
    if ((token === import61.Overlay)) { return this._Overlay_74; }
    if ((token === import25.MdDialog)) { return this._MdDialog_75; }
    if ((token === import62.MdIconRegistry)) { return this._MdIconRegistry_76; }
    if ((token === import32.MdSnackBar)) { return this._MdSnackBar_77; }
    if ((token === import63.PaginationService)) { return this._PaginationService_78; }
    if ((token === import64.AlbumService)) { return this._AlbumService_79; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__41.ngOnDestroy();
    this._DomSharedStylesHost_49.ngOnDestroy();
  }
}
export const MaterialAppModuleNgFactory:import0.NgModuleFactory<import1.MaterialAppModule> = new import0.NgModuleFactory(MaterialAppModuleInjector,import1.MaterialAppModule);