/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.photos[_ngcontent-%COMP%] {\n    display: flex;\n    justify-content: space-between;\n    flex-direction: row;\n    width: 100%;\n}\napp-photo[_ngcontent-%COMP%] {\n    display: flex;\n    width: 100%;\n    flex-wrap: wrap;\n    justify-content: space-around;\n}'];