/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/album/photo/photo.component';
import * as import1 from '@angular/core/src/change_detection/change_detection_util';
import * as import2 from '@angular/core/src/linker/view';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/metadata/view';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/constants';
import * as import8 from '@angular/core/src/linker/component_factory';
import * as import9 from '../../../../app/album/album.service';
import * as import10 from './photo.component.scss.shim.ngstyle';
import * as import11 from '@angular/material/card/card';
import * as import12 from '../../../node_modules/@angular/material/card/card.ngfactory';
import * as import13 from '../../../node_modules/@angular/material/core/compatibility/style-compatibility.ngfactory';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '@angular/core/src/linker/element_ref';
import * as import16 from '@angular/material/core/compatibility/style-compatibility';
import * as import17 from '@angular/core/src/security';
import * as import18 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/common/src/directives/ng_for';
export class Wrapper_PhotoComponent {
  /*private*/ _eventHandler:Function;
  context:import0.PhotoComponent;
  /*private*/ _changed:boolean;
  /*private*/ _expr_0:any;
  constructor(p0:any) {
    this._changed = false;
    this.context = new import0.PhotoComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
  }
  ngOnDetach(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  check_album(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import3.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this._changed = true;
      this.context.album = currValue;
      this._expr_0 = currValue;
    }
  }
  ngDoCheck(view:import2.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import2.AppView<any>,componentView:import2.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import2.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_PhotoComponent_Host:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.None,([] as any[]),{});
class View_PhotoComponent_Host0 extends import2.AppView<any> {
  _el_0:any;
  compView_0:import2.AppView<import0.PhotoComponent>;
  _PhotoComponent_0_3:Wrapper_PhotoComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PhotoComponent_Host0,renderType_PhotoComponent_Host,import6.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'app-photo',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_PhotoComponent0(this.viewUtils,this,0,this._el_0);
    this._PhotoComponent_0_3 = new Wrapper_PhotoComponent(this.injectorGet(import9.AlbumService,this.parentIndex));
    this.compView_0.create(this._PhotoComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import8.ComponentRef_<any>(0,this,this._el_0,this._PhotoComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PhotoComponent) && (0 === requestNodeIndex))) { return this._PhotoComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PhotoComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const PhotoComponentNgFactory:import8.ComponentFactory<import0.PhotoComponent> = new import8.ComponentFactory<import0.PhotoComponent>('app-photo',View_PhotoComponent_Host0,import0.PhotoComponent);
const styles_PhotoComponent:any[] = [import10.styles];
class View_PhotoComponent1 extends import2.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  compView_2:import2.AppView<import11.MdCard>;
  _MdCard_2_3:import12.Wrapper_MdCard;
  _StyleCompatibility_2_4:import13.Wrapper_StyleCompatibility;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _MdCardFooter_6_3:import12.Wrapper_MdCardFooter;
  _StyleCompatibility_6_4:import13.Wrapper_StyleCompatibility;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_PhotoComponent1,renderType_PhotoComponent,import6.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_15 = import1.UNINITIALIZED;
    this._expr_16 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','container'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'md-card',new import3.InlineArray2(2,'class','md-primary'),(null as any));
    this.compView_2 = new import12.View_MdCard0(this.viewUtils,this,2,this._el_2);
    this._MdCard_2_3 = new import12.Wrapper_MdCard();
    this._StyleCompatibility_2_4 = new import13.Wrapper_StyleCompatibility(this.renderer,new import15.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,(null as any),'img',new import3.InlineArray8(6,'height','150','md-card-image','','width','150'),(null as any));
    this._text_5 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,(null as any),'md-card-footer',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._MdCardFooter_6_3 = new import12.Wrapper_MdCardFooter();
    this._StyleCompatibility_6_4 = new import13.Wrapper_StyleCompatibility(this.renderer,new import15.ElementRef(this._el_6));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this.compView_2.create(this._MdCard_2_3.context);
    this._text_9 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.MdCardFooter) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MdCardFooter_6_3.context; }
    if (((token === import16.StyleCompatibility) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._StyleCompatibility_6_4.context; }
    if (((token === import11.MdCard) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MdCard_2_3.context; }
    if (((token === import16.StyleCompatibility) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._StyleCompatibility_2_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._MdCard_2_3.ngDoCheck(this,this._el_2,throwOnChange)) { this.compView_2.markAsCheckOnce(); }
    this._StyleCompatibility_2_4.ngDoCheck(this,this._el_2,throwOnChange);
    this._MdCardFooter_6_3.ngDoCheck(this,this._el_6,throwOnChange);
    this._StyleCompatibility_6_4.ngDoCheck(this,this._el_6,throwOnChange);
    const currVal_15:any = this.context.$implicit.thumbnailUrl;
    if (import3.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import17.SecurityContext.URL,currVal_15));
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import3.inlineInterpolate(1,'',this.context.$implicit.title,'');
    if (import3.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_7,currVal_16);
      this._expr_16 = currVal_16;
    }
    this.compView_2.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_2.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  visitProjectableNodesInternal(nodeIndex:number,ngContentIndex:number,cb:any,ctx:any):void {
    if (((nodeIndex == 2) && (ngContentIndex == 0))) {
      cb(this._text_3,ctx);
      cb(this._el_4,ctx);
      cb(this._text_5,ctx);
      cb(this._el_6,ctx);
      cb(this._text_8,ctx);
    }
  }
}
var renderType_PhotoComponent:import4.RenderComponentType = import3.createRenderComponentType('',0,import5.ViewEncapsulation.Emulated,styles_PhotoComponent,{});
export class View_PhotoComponent0 extends import2.AppView<import0.PhotoComponent> {
  _anchor_0:any;
  /*private*/ _vc_0:import14.ViewContainer;
  _TemplateRef_0_5:any;
  _NgFor_0_6:import18.Wrapper_NgFor;
  constructor(viewUtils:import3.ViewUtils,parentView:import2.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_PhotoComponent0,renderType_PhotoComponent,import6.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import8.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._vc_0 = new import14.ViewContainer(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import19.TemplateRef_(this,0,this._anchor_0);
    this._NgFor_0_6 = new import18.Wrapper_NgFor(this._vc_0.vcRef,this._TemplateRef_0_5,this.parentView.injectorGet(import20.IterableDiffers,this.parentIndex),this.ref);
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [this._anchor_0]),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import21.NgFor) && (0 === requestNodeIndex))) { return this._NgFor_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.context.photos;
    this._NgFor_0_6.check_ngForOf(currVal_0_0_0,throwOnChange,false);
    this._NgFor_0_6.ngDoCheck(this,this._anchor_0,throwOnChange);
    this._vc_0.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._vc_0.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import2.AppView<any> {
    if ((nodeIndex == 0)) { return new View_PhotoComponent1(this.viewUtils,this,0,this._anchor_0,this._vc_0); }
    return (null as any);
  }
}