/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.container[_ngcontent-%COMP%] {\n    width: 150px;\n    float: left;\n    margin: 10px;\n\n    .md-card-footer {\n        white-space: nowrap;\n        overflow: hidden;\n        text-overflow: ellipsis;\n        padding: 5px;\n        line-height: 32px;\n        vertical-align: middle;\n        width: 90%\n    }\n}'];